# Site settings
title: Geoinquietos
#email: xurxosanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este sitio muestra los diferentes grupos de geoinquietos y c√≥mo contactar
  con ellos.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://test.geoinquietos.org" # the base hostname & protocol for your site

#twitter_username: geoinquietos_es
#github_username:  jsanz

# Build settings
markdown: kramdown
highlighter: pygments

# Collections
collections:
  groups:
    output: true
    permalink: /grupos/:path/
  contacts:
    output: true
    permalink: /contactos/:path/

defaults:
  - scope:
      path: ""
      type: groups
    values:
      layout: group
  - scope:
      path: ""
      type: contacts
    values:
      layout: contact

cartodb:
  center:
    lat: 5
    lon: -44
  zoom: 2
  group_zoom: 7
  sql: "SELECT *, replace(_group,'Geoinquietos ','') as label FROM jsanz.groups"
